my_project/employeer/urls.py
from django.urls import path
from . import views

app_name = 'employeer'

urlpatterns = [
    path('employeer_profile/', views.employeer_profile, name='employeer_profile'),
    path('add_job/', views.add_job, name='add_job'),
    path('employeer_home/', views.employeer_home, name='employeer_home'),
    path('job_application/', views.job_application, name='job_application'),
    path('update_status/<int:application_id>/', views.update_status, name='update_status'),
    path('edit_job/<int:job_id>/', views.edit_job, name='edit_job'),
    path('delete_job/<int:job_id>/', views.delete_job, name='delete_job'),
    
]

my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('job_seeker/', include('job_seeker.urls')),
    path('employeer/', include('employeer.urls')),
    path('admin1/', include('admin1.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name='home'),
    path('login/', views.user_login, name='login'),
    path('signup/', views.user_signup, name='signup'),
    path('logout/', views.user_logout, name='logout'),
    path('home1/', views.home1, name='home1'),
    path('complaint/', views.complaint, name='complaint'),
     path('view_complaint/', views.view_complaint, name='view_complaint'),
    
    
    
    
]

my_project/employeer/models.py
from django.db import models
from django.contrib.auth.models import User 
from users.models import Company
from django.utils import timezone
class Job(models.Model):
    company_name = models.ForeignKey(Company, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    user_email = models.EmailField(blank=True)
    title = models.CharField(max_length=100)
    description = models.TextField()
    
    required_qualifications = models.TextField()
    desired_qualifications = models.TextField()
    responsibilities = models.TextField()
    application_deadline = models.DateField()
    salary_range = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    date_added = models.DateTimeField(default=timezone.now)
    employment_type = models.CharField(max_length=20, choices=[('work_from_home', 'Work From Home'), ('work_from_office', 'Work From Office'), ('hybrid', 'Hybrid')])
    company_benefits = models.TextField()
    how_to_apply = models.TextField()
    other_information = models.TextField()
    industry_type = [
        ('IT', 'Information Technology'),
        ('Healthcare', 'Healthcare'),
        ('Finance', 'Finance'),
        ('Education', 'Education'),
        ('Manufacturing', 'Manufacturing'),
    ]
    industry = models.CharField(max_length=20, choices=industry_type,default='IT')
    def save(self, *args, **kwargs):
        if self.user:
            self.user_email = self.user.email
        super().save(*args, **kwargs)

    def __str__(self):
        return self.company_name

my_project/employeer/forms.py
from django import forms
from users.models import UserProfile, Company

from .models import Job

class ProfileForm(forms.ModelForm):
    email = forms.EmailField(label='Email')
    company_name = forms.CharField(label='Company Name')
    company = Company.objects.first()  
    DESIGNATION_CHOICES = company.DESIGNATION_CHOICES

    designation = forms.ChoiceField(
        choices=DESIGNATION_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = UserProfile
        fields = ['email', 'designation','company_name']

class add_jobForm(forms.ModelForm):
    
    class Meta:
        model = Job
        fields = '__all__'
        exclude = ['company_name','user','user_email']
        
        user_type = forms.ChoiceField(
        choices=[('job_seeker', 'Job Seeker'), ('employer', 'Employer')],
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=True,
        label='User Type'
    )
        widgets = {
            'application_deadline': forms.DateInput(attrs={'type': 'date'})
        }
class JobForm(forms.ModelForm):
    WORK_LOCATION_CHOICES = [
        ('hybrid', 'Hybrid'),
        ('work_from_home', 'Work from Home'),
        ('work_from_office', 'Work from Office'),
    ]
    
    employment_type = forms.ChoiceField(
        choices=WORK_LOCATION_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=True,
        label='Work Location'
    )
    
    class Meta:
        model = Job
        fields = ['title', 'description', 'salary_range', 'application_deadline', 'location','required_qualifications','desired_qualifications','responsibilities'
                  ,'company_benefits','how_to_apply','other_information', 'employment_type']
    

my_project/employeer/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm
from .forms import add_jobForm
from .models import Job
from django.db.models import Q
from job_seeker.models import JobApplication
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.http import HttpResponseServerError
from .forms import JobForm
@login_required
def employeer_profile(request):
    employeer = request.user
    user_email = request.user.email
    user_type = request.user.userprofile.user_type
    company_name = request.user.company.company_name
    designation = request.user.company.designation

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
        if form.is_valid():
            employeer.email = form.cleaned_data['email']
            employeer.save()

            
            company = request.user.company
            company.company_name=form.cleaned_data['company_name']
            company.designation = form.cleaned_data['designation']
            company.save()
            form.save()
            return redirect('employeer:employeer_profile')
    else:
        form = ProfileForm(instance=request.user.userprofile, initial={'email': user_email, 'designation': designation,'company_name':company_name})

    return render(request, 'employeer/employeer_profile.html', {
        'employeer': employeer,
        'user_email': user_email,
        'user_type': user_type,
        'form': form,
        'company_name': company_name,
        'designation': designation
    })
def add_job(request):
    company_name = request.user.company
    user = request.user 
    user_email = request.user.email
    if request.method == 'POST':
        form = add_jobForm(request.POST)
        if form.is_valid():
            job_listing = form.save(commit=False)
            job_listing.company_name = company_name 
            job_listing.user = user
            job_listing.user_email = user_email 
            job_listing.save()
            return redirect('employeer:add_job')
    else:
        form = add_jobForm()
    return render(request, 'employeer/add_job.html', {'form': form, 'company_name': company_name,'user': user,'user_email':user_email})

   
def employeer_home(request):
    company_name = request.user.company
    search_query = request.GET.get('search')
    job_listings = Job.objects.filter(company_name=company_name)
    
    if search_query:
        job_listings = job_listings.filter(
            Q(title__icontains=search_query) |
            Q(description__icontains=search_query)|
            Q(location__icontains=search_query)
        )

    job_listings = job_listings.order_by('-id')
    
    return render(request, 'employeer/employeer_home.html', {'job_listings': job_listings})
def job_application(request):
    
    user_company_jobs = request.user.company.job_set.all()
    job_ids = user_company_jobs.values_list('id', flat=True)
    application = JobApplication.objects.filter(job_id__in=job_ids)
    return render(request, 'employeer/job_application.html', {'application': application})
def update_status(request, application_id):
    application = get_object_or_404(JobApplication, id=application_id)
    
    if request.method == 'POST':
        new_status = request.POST.get('status')
        if new_status in ['ACCEPTED', 'REJECTED']:
            old_status = application.status
            application.status = new_status
            application.save()
            
            # Send email to the job seeker
            subject = f"Application Status Update for Job: {application.job.title}"
            job_seeker_email = application.email
            job_seeker_name = application.full_name
            email_template = 'employeer/job_seeker_status_notification.html'
            email_context = {
                'job_title': application.job.title,
                'new_status': new_status,
                'old_status': old_status,
                'job_seeker_name': job_seeker_name,
            }
            if new_status == 'ACCEPTED':
                email_context['message'] = "Congratulations! Your application has been accepted for the position."
            elif new_status == 'REJECTED':
                email_context['message'] = "We regret to inform you that your application has been rejected for the position."
            
            try:
                send_mail(subject, render_to_string(email_template, email_context), None, [job_seeker_email], fail_silently=False)
            except Exception as e:
                return HttpResponseServerError(f'An error occurred while sending email notification: {e}')
    
    return redirect('employeer:job_application')
def edit_job(request, job_id):
    job = get_object_or_404(Job, id=job_id)
    if request.method == 'POST':
        form = JobForm(request.POST, instance=job)
        if form.is_valid():
            form.save()
            return redirect('employeer:employeer_home')
    else:
        form = JobForm(instance=job)
    return render(request, 'employeer/edit_job.html', {'form': form})

def delete_job(request, job_id):
    job = get_object_or_404(Job, id=job_id)
    if request.method == 'POST':
        job.delete()
        return redirect('employeer:employeer_home')
    return render(request, 'employeer/delete_job_confirm.html', {'job': job})

my_project/employeer/templates/employeer/add_job.html
{% include 'users/navbar.html' %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Job Seeker Profile</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .container1 {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #333;
            text-align: center;
        }
        form {
            margin-top: 20px;
        }
        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }
        input[type="text"],
        input[type="email"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 16px;
        }
        textarea {
            height: 100px;
        }
        button {
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            padding: 10px 20px;
            cursor: pointer;
            font-size: 16px;
        }
        button:hover {
            background-color: #0056b3;
        }
        .error-message {
            color: red;
            margin-top: 5px;
        }
    </style>
</head>
<body>
    <div class="container1">
      

<h2>Add Job</h2>




{% block scripts %}
<script>
  // Initialize date picker
  document.addEventListener('DOMContentLoaded', function() {
    const datePickerInput = document.querySelector('input[type="date"]');
    if (datePickerInput) {
      datePickerInput.min = new Date().toISOString().split("T")[0];
    }
  });
</script>
{% endblock %}

        
         
       
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="id_company_name">Company Name:</label>
            <input type="text" id="id_company_name" name="company_name" value="{{ company_name }}" readonly>
            <label for="id_user">user id <i class="fa fa-id-badge" aria-hidden="true"></i>:</label>
            <input type="text" id="id_user" name="user.id" value="{{ user.id }}" readonly>
            <label for="id_user_email">User Email:</label>
            <input type="email" id="id_user_email" name="user_email" value="{{ user.email }}" readonly>
            
            {{ form.as_p }}
            
            <button type="submit">Save</button>
        </form>
    </div>
</body>
</html>

my_project/employeer/templates/employeer/delete_job_confirm.html
{% include 'users/navbar.html' %}


{% block content %}
    <h1>Delete Job</h1>
    <p>Are you sure you want to delete the job "{{ job.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm Delete</button>
        <a href="{% url 'employeer:employeer_home' %}">Cancel</a>
    </form>
{% endblock %}

my_project/employeer/templates/employeer/edit_job.html
{% include 'users/navbar.html' %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Job Seeker Profile</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .container1 {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #333;
            text-align: center;
        }
        form {
            margin-top: 20px;
        }
        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }
        input[type="text"],
        input[type="email"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 16px;
        }
        textarea {
            height: 100px;
        }
        button {
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            padding: 10px 20px;
            cursor: pointer;
            font-size: 16px;
        }
        button:hover {
            background-color: #0056b3;
        }
        .error-message {
            color: red;
            margin-top: 5px;
        }
    </style>
</head>
<body>
    <div class="container1">
      

<h2>Edit Job</h2>




{% block scripts %}
<script>
  
  document.addEventListener('DOMContentLoaded', function() {
    const datePickerInput = document.querySelector('input[type="date"]');
    if (datePickerInput) {
      datePickerInput.min = new Date().toISOString().split("T")[0];
    }
  });
</script>
{% endblock %}

        
         
       
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            
            {{ form.as_p }}
            
            <button type="submit">Save</button>
        </form>
    </div>
</body>
</html>

my_project/employeer/templates/employeer/employeer_home.html
{% include 'users/navbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employeer Home</title>
    
    <style>
       
        .job-listing-container {
            display: flex;
            flex-wrap: wrap;
        }
        .job-listing {
            width: calc(33.33% - 50px); 
            border: 1px solid #ccc;
            margin: 3px;
            padding: 20px;
        }
        .job-listing h2 {
            font-size: 30px;
            margin-bottom: 15px;
        }
        .job-listing p {
            margin: 5px 0;
            font-size: 20px;
        }
    </style>
</head>
<body>
    <h1>Welcome to Employeer Home</h1>
    
    <!-- Search box -->
    <form method="GET" action="{% url 'employeer:employeer_home' %}">
        <input type="text" name="search" placeholder="Search by title">
        <button type="submit">Search</button>
    </form>
    <!-- Search box end here-->
    
    <!-- Display job listings -->
    <div class="job-listing-container">
        {% for job in job_listings %}
        <div class="job-listing">
            <h2>{{ job.title }}</h2>
            <p><strong>Job Id:</strong> {{job.id}}</p>
            <p><strong>Company:</strong> {{ job.company_name }}</p>
            <p><strong>Salary:</strong> {{ job.salary_range }}</p>
            <p><strong>Date Posted:</strong> {{ job.date_added }}</p>
            <p><strong>Deadline:</strong> {{ job.application_deadline }}</p>
            
            <form action="{% url 'employeer:edit_job' job.id %}">
                <button type="submit">Edit</button>
            </form>
            <form action="{% url 'employeer:delete_job' job.id %}" onsubmit="return confirm('Are you sure you want to delete this job?');">
                <button type="submit">Delete</button>
            </form>
        </div>
        {% empty %}
        <p>No job listings available.</p>
        {% endfor %}
    </div>
    <!-- Display job listings here -->
</body>
</html>

my_project/employeer/templates/employeer/employeer_profile.html
{% include 'users/navbar.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Job Seeker Profile</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .container1 {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #333;
            text-align: center;
        }
        form {
            margin-top: 20px;
        }
        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }
        input[type="text"],
        input[type="email"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 16px;
        }
        textarea {
            height: 100px;
        }
        button {
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            padding: 10px 20px;
            cursor: pointer;
            font-size: 16px;
        }
        button:hover {
            background-color: #0056b3;
        }
        .error-message {
            color: red;
            margin-top: 5px;
        }
    </style>
</head>
<body>
    <div class="container1">
        <h1>Welcome, {{ employeer.username }}</h1>
        <h4>User Type: {{ user_type }}</h4>
        <h4>Company Name: {{ company_name }}</h4>
        <h4>Designation: {{ designation }}</h4>
        {% if form.errors %}
            <p class="error-message">There was an error in your form submission. Please correct the errors below.</p>
        {% endif %}
        
       
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save</button>
        </form>
    </div>
</body>
</html>

my_project/employeer/templates/employeer/job_application.html
{% include 'users/navbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    
    <style>
        
        
        .job-listing-container {
            display: flex;
            flex-wrap: wrap;
        }
        .job-listing {
            width: calc(33.33% - 50px); 
            border: 1px solid #ccc;
            margin: 3px;
            padding: 20px;
        }
        .job-listing h2 {
            font-size: 30px;
            margin-bottom: 15px;
        }
        .job-listing p {
            margin: 5px 0;
            font-size: 20px;
        }
    </style>
</head>
<body>
    
    <h1>Applied Job</h1>
    
   
    
    
    <div class="job-listing-container">
        {% for item in application %}
        <div class="job-listing">
            <p><strong>Job Id:</strong> {{ item.job_id}}</p>
            <p><strong>Username:</strong> {{ item.user.username }}</p>
            <p><strong>Coverletter:</strong> {{ item.cover_letter }}</p>
            <p><strong>Resume:</strong> {% if item.resume %}
                <a href="{{ item.resume.url }}" class="resume-link" download>Download Resume</a>
                {% endif %}</p>
            <p><strong>Email:</strong> {{ item.email }}</p>
            <p><strong>Status:</strong> {{ item.status }}</p>
            
            {% if item.status not in 'ACCEPTED,REJECTED' %}
            <form method="POST" action="{% url 'employeer:update_status' item.id %}">
                {% csrf_token %}
                <button type="submit" name="status" value="ACCEPTED">Accept</button>
                <button type="submit" name="status" value="REJECTED">Reject</button>
            </form>
            {% endif %}
        </div>
        {% empty %}
        <p>No job listings available.</p>
        {% endfor %}
    </div>
</body>
</html>

my_project/employeer/templates/employeer/job_seeker_status_notification.html
Application Status Update

Dear {{ job_seeker_name }},
    
    We are writing to inform you about the status update for your application for the position of "{{ job_title }}".
    
    Old Status: {{ old_status }}
    New Status: {{ new_status }}
    
    {{ message }}
    
    Thank you.