my_project/job_seeker/urls.py
from django.urls import path
from . import views

app_name = 'job_seeker'

urlpatterns = [
    path('profile/', views.job_seeker_profile, name='profile'),
    path('apply_job/<int:job_id>', views.apply_job, name='apply_job'), 
    path('job_detail/<int:job_id>/', views.job_detail, name='job_detail'),
    path('job_applied/', views.job_applied, name='job_applied'), 


]

my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('job_seeker/', include('job_seeker.urls')),
    path('employeer/', include('employeer.urls')),
    path('admin1/', include('admin1.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name='home'),
    path('login/', views.user_login, name='login'),
    path('signup/', views.user_signup, name='signup'),
    path('logout/', views.user_logout, name='logout'),
    path('home1/', views.home1, name='home1'),
    path('complaint/', views.complaint, name='complaint'),
     path('view_complaint/', views.view_complaint, name='view_complaint'),
    
    
    
    
]

my_project/job_seeker/models.py
from django import forms
from django.db import models
from django.contrib.auth.models import User
from users.models import UserProfile
from employeer.models import Job

class JobApplication(models.Model):
    
    STATUS_CHOICES = [
        ('APPLIED', 'Applied'),
        ('ACCEPTED', 'Accepted'),
        ('REJECTED', 'Rejected'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    UserProfile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    username = models.CharField(max_length=100)
    email = models.EmailField()
    resume = models.FileField(upload_to='resumes/', null=True, blank=True)
    cover_letter = models.TextField()
    full_name = models.CharField(max_length=255) 
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='APPLIED')

    def __str__(self):
        return f"{self.user.username} - {self.job.title} -{self.full_name} - {self.get_status_display()}-"

my_project/job_seeker/forms.py
from django import forms
from .models import UserProfile  # Remove this line
from .models import JobApplication
class ProfileForm(forms.ModelForm):
    email = forms.EmailField(
        max_length=100,
        required=True,
        help_text='Enter Email Address',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
    )

    class Meta:
        model = UserProfile
        fields = ['email', 'cover_letter', 'resume']



class JobApplicationForm(forms.ModelForm):
    email = forms.EmailField(
        max_length=100,
        required=True,  
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
    )
    
    class Meta:
        model = JobApplication
        fields = ['full_name','username', 'email', 'resume', 'cover_letter']

my_project/job_seeker/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm
from django.shortcuts import render, get_object_or_404
from employeer.models import Job
from .forms import JobApplicationForm
from .models import JobApplication
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponseServerError
@login_required
def job_seeker_profile(request):
    
    job_seeker = request.user
    user_email = request.user.email
    user_type = request.user.userprofile.user_type
    
    
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
        if form.is_valid():
           
            job_seeker.email = form.cleaned_data['email']
            job_seeker.save()
            form.save()
            return redirect('job_seeker:profile')
    else:
        form = ProfileForm(instance=request.user.userprofile, initial={'email': user_email})

    
    return render(request, 'job_seeker/profile.html', {'job_seeker': job_seeker, 'user_email': user_email, 'user_type': user_type, 'form': form})
def job_detail(request, job_id):
    job = get_object_or_404(Job, id=job_id)
    user = request.user
    user_has_applied = JobApplication.objects.filter(user=user, job=job).exists()
    context = {'job': job, 'user_has_applied': user_has_applied}
    return render(request, 'job_seeker/job_detail.html', context)

@login_required
def apply_job(request, job_id):
    job = get_object_or_404(Job, id=job_id)
    user_email = request.user.email
    job_seeker = request.user
    employeer = request.user
    user_email = request.user.email
    user_type = request.user.userprofile.user_type
    cover_letter = request.user.userprofile.cover_letter
    resume = request.user.userprofile.resume
    full_name = request.user.userprofile.full_name
    
    if request.method == 'POST':
        form = JobApplicationForm(request.POST, request.FILES)
        if form.is_valid():
            application = form.save(commit=False)
            application.user = request.user
            application.job = job
            application.username = request.user.username
            application.email = form.cleaned_data['email']
            application.full_name = request.user.userprofile.full_name
            application.UserProfile = request.user.userprofile
            
            if not form.cleaned_data['resume']:
                
                application.resume = resume
            
            application.save()
            employer_email = job.user_email
            subject_employeer = f"New Job Application for {job.title}"
            subject_job_seeker = f"Your Job Application Submmited for {job.title}"
            applicant_name = request.user.userprofile.full_name
            applicant_email = request.user.email
            job_status = job_seeker.jobapplication_set.filter(job=job).first().status
            email_template_employeer = 'job_seeker/employer_notification_email.html'
            email_template_job_seeker = 'job_seeker/job_seeker_notification_email.html'
            email_context_employer = {
                'job_title': job.title,
                'applicant_name': applicant_name,
                'applicant_email': applicant_email,
            }
            email_context_job_seeker = {
                'job_title': job.title,
                'applicant_name': applicant_name,
                'status':job_status
            }
            try:
                send_mail(subject_employeer, render_to_string(email_template_employeer, email_context_employer), user_email, [employer_email], fail_silently=False)
                send_mail(subject_job_seeker, render_to_string(email_template_job_seeker, email_context_job_seeker), user_email, [applicant_email], fail_silently=False)
            except BadHeaderError:
                return HttpResponseServerError('Invalid header found.')
            except Exception as e:
                return HttpResponseServerError(f'An error occurred: {e}')
            return redirect('home')
            
    else:
        
        initial_data = {'email': user_email, 'username': request.user.username, 'cover_letter': cover_letter, 'full_name': full_name}
        
        if resume:
            initial_data['resume'] = resume
        form = JobApplicationForm(initial=initial_data)
    
    return render(request, 'job_seeker/apply_job.html', {'form': form, 'job': job, 'user_email': user_email, 'job_seeker': job_seeker, 'user_type': user_type,'full_name':full_name})

def job_applied(request):
    user = request.user
    
    job_applied = JobApplication.objects.filter(user=user)
    return render(request, 'job_seeker/job_applied.html', {'job_applied': job_applied})

my_project/job_seeker/templates/job_seeker/apply_job.html
{% include 'users/navbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apply for Job</title>
</head>
<body>
    <h1>Apply for Job</h1>
    <h1>Welcome, {{ user.userprofile.full_name }}</h1>
    <p>Job Title: {{ job.title }}</p>
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit Application</button>
    </form>
</body>
</html>

my_project/job_seeker/templates/job_seeker/employer_notification_email.html
Dear Employer,
A new job application has been submitted for the position of {{ job_title }} by {{ applicant_name }}.
Please review the application.

my_project/job_seeker/templates/job_seeker/job_applied.html
{% include 'users/navbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    
    <style>
        
        
        .job-listing-container {
            display: flex;
            flex-wrap: wrap;
        }
        .job-listing {
            width: calc(33.33% - 50px); 
            border: 1px solid #ccc;
            margin: 3px;
            padding: 20px;
        }
        .job-listing h2 {
            font-size: 30px;
            margin-bottom: 15px;
        }
        .job-listing p {
            margin: 5px 0;
            font-size: 20px;
        }
    </style>
</head>
<body>
    
    <h1>Applied Job</h1>
    
   
    
    
    <div class="job-listing-container">
        {% for application in job_applied %}
        <div class="job-listing">
            <h2>{{ job.title }}</h2>
            <p><strong>Company:</strong> {{ application.job.company_name }}</p>
            <p><strong>Position:</strong> {{ application.job.title }}</p>
            <p><strong>Status:</strong> {{ application.status }}</p>
           
        </div>
        {% empty %}
        <p>No job listings available.</p>
        {% endfor %}
    </div>
</body>
</html>

my_project/job_seeker/templates/job_seeker/job_detail.html
{% include 'users/navbar.html' %}
{% block content %}
    <h2>{{ job.title }}</h2>
    <p><strong>Company:</strong> {{ job.company_name }}</p>
    <p><strong>Salary:</strong> {{ job.salary_range }}</p>
    <p><strong>Date Posted:</strong> {{ job.date_added }}</p>
    <p><strong>Deadline:</strong> {{ job.application_deadline }}</p>
    <p><strong>Description:</strong> {{ job.description }}</p>
    <p><strong>Responsibilities:</strong> {{ job.responsibilities }}</p>
    <p><strong>Work Mode:</strong> {{ job.employment_type}}</p>
    <p><strong>Location:</strong> {{ job.location }}</p>
    <p><strong>Benefits:</strong> {{ job.company_benefits}}</p>
    <p><strong>Required Qualifications:</strong> {{ job.required_qualifications}}</p>
    <p><strong>Desired Qualifications:</strong> {{ job.desired_qualifications}}</p>
    <p><strong>How To Apply:</strong> {{ job.how_to_apply}}</p>
    <p><strong>Other Information:</strong> {{ job.other_information}}</p>



    
   
    {% if user_has_applied %}
        <p><strong>Status:</strong> Applied</p>
    {% else %}
        
        <a href="{% url 'job_seeker:apply_job' job.id %}">Apply Now</a>
    {% endif %}
{% endblock %}

my_project/job_seeker/templates/job_seeker/job_seeker_notification_email.html
Job Application Status Update

    Dear {{ applicant_name }},
    Your job application for the position of {{ job_title }} has been {{ status }}.

my_project/job_seeker/templates/job_seeker/profile.html
{% include 'users/navbar.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Job Seeker Profile</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .container1 {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #333;
            text-align: center;
        }
        form {
            margin-top: 20px;
        }
        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }
        input[type="text"],
        input[type="email"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
            font-size: 16px;
        }
        textarea {
            height: 100px;
        }
        button {
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            padding: 10px 20px;
            cursor: pointer;
            font-size: 16px;
        }
        button:hover {
            background-color: #0056b3;
        }
        .error-message {
            color: red;
            margin-top: 5px;
        }
    </style>
</head>
<body>
    <div class="container1">
        <h1>Welcome, {{ user.userprofile.full_name}}</h1>
        <p>User Type: {{ user_type }}</p>
        
       
        {% if form.errors %}
            <p class="error-message">There was an error in your form submission. Please correct the errors below.</p>
        {% endif %}

        
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save</button>
        </form>
    </div>
</body>
</html>